{
    "name": "Aicia portal requests",
    "summary": """Aicia portal requests""",
    "version": "17.0.1.0.0",
    "description": """Aicia portal requests""",
    "company": "Xtendoo",
    "website": "http://www.xtendoo.es",
    "author": "Dani Domínguez",
    "category": "Website",
    "depends": [
        "website",
        "portal",
        "account",
        "mail",
        "l10n_es_edi_facturae",
        "hr",
        "hr_expense",
        "web",
    ],
    "license": "AGPL-3",
    "data": [
        'security/ir.model.access.csv',
        'data/res_group_data.xml',
        'data/type_approval.xml',
        'data/dashboard.xml',
        'views/portal_approval_request_template.xml',
        'views/portal_hr_employee_requests_template.xml',
        'views/portal_hr_employee_intern_requests_template.xml',
        'views/portal_hr_expensive_requests_template.xml',
        'views/portal_invoice_requests_template.xml',
        'views/portal_project_end_request_template.xml',
        'views/portal_project_requests_template.xml',
        'views/portal_purchase_order_requests_template.xml',
        'views/interface/menu.xml',
        'views/interface/portal_project_request.xml',
        'views/interface/aicia_approval_documents.xml',
        'views/interface/aicia_type_approval.xml',
        'views/interface/portal_invoice_request.xml',
        'views/interface/portal_employee_request.xml',
        'views/interface/portal_employee_intern_request.xml',
    ],
    "installable": True,
    'application': False,
}
