{
    "name": "Aicia portal requests",
    "summary": """Aicia portal requests""",
    "version": "19.0.1.0.0",
    "description": """Aicia portal requests""",
    "company": "Xtendoo",
    "website": "http://www.xtendoo.es",
    "author": "Dani Domínguez",
    "category": "Website",
    "depends": [
        "website",
        "portal",
        "account",
        "mail",
        "l10n_es_edi_facturae",
        "hr",
        "hr_expense",
        "web",
        "sign",
        "project",
        "send_draft_invoices",
        "xtendoo_invoice_import_gemini_ai"
    ],
    "license": "AGPL-3",
    "data": [
        'security/ir.model.access.csv',
        'data/res_group_data.xml',
        'data/type_approval.xml',
        'data/dashboard.xml',
        'views/portal_approval_request_template.xml',
        'views/portal_hr_employee_requests_template.xml',
        'views/portal_hr_employee_intern_requests_template.xml',
        'views/portal_hr_expensive_requests_template.xml',
        'views/portal_invoice_requests_template.xml',
        'views/portal_project_end_request_template.xml',
        'views/portal_project_requests_template.xml',
        'views/portal_purchase_order_requests_template.xml',
        'views/interface/menu.xml',
        'views/interface/portal_project_request.xml',
        'views/interface/aicia_approval_documents.xml',
        'views/interface/aicia_type_approval.xml',
        'views/interface/portal_invoice_request.xml',
        'views/interface/portal_employee_request.xml',
        'views/interface/portal_employee_intern_request.xml',
        'views/interface/work_group_views.xml',
        'views/interface/account_analytic_inherit_views.xml',  # Nueva vista heredada
        'views/interface/etiqueta_categoria_views.xml',
        'views/interface/portal_hr_expensive_request.xml',
        'views/interface/ir_attachment_views.xml',
        'views/portal_user_templates/portal_user_templates.xml',
        'views/portal_user_templates/portal_my_home_requests.xml',
        'views/portal_user_templates/portal_my_expenses_list.xml',
        'views/portal_user_templates/portal_my_expense_detail.xml',
        'views/portal_user_templates/hr_expensive_request_thank_you.xml',
        'views/portal_user_templates/portal_my_invoices_list.xml',
        'views/portal_user_templates/portal_my_invoice_detail.xml',
        'views/portal_user_templates/portal_invoice_view.xml',
        'views/portal_user_templates/invoice_request_thank_you.xml',
        'views/portal_user_templates/portal_my_documents_list.xml',
        'views/portal_user_templates/portal_my_document_detail.xml',
        'views/portal_user_templates/document_request_thank_you.xml',
        'views/portal_user_templates/portal_my_projects.xml',
        'views/portal_user_templates/portal_my_project_requests_list.xml',
        'views/portal_user_templates/project_request_thank_you.xml',
        'security/dashboard_permision.xml',
        'wizards/purchase_request_reject_wizard.xml',
        'wizards/invoice_request_reject_wizard.xml',
    ],
    "installable": True,
    'application': False,
}
