{
    'name': 'Recodificación contable PGC 2008',
    'version': '19.0.1.0.0',
    'category': 'Accounting/Accounting',
    'summary': 'Herramienta de recodificación contable PGC 2008',
    'author': 'Xtendoo',
    'website': 'https://xtendoo.es',
    'depends': ['account', 'aicia_account_menu'],
    'data': [
        'security/ir.model.access.csv',
        'data/aicia_account_pgc_recode_rule_data.xml',
        'views/aicia_account_pgc_recode_rule_views.xml',
        'views/aicia_account_pgc_recode_batch_views.xml',
        'views/aicia_account_pgc_recode_line_views.xml',
        'views/aicia_pgc_recode_import_wizard_views.xml',
        'views/aicia_pgc_recode_simulation_wizard_views.xml',
        'views/aicia_pgc_recode_apply_wizard_views.xml',
        'views/menus.xml',
    ],
    'installable': True,
    'application': False,
    'auto_install': False,
    'license': 'AGPL-3',
}
