from . import portal_approval_request_model
from . import portal_hr_employee_request_model
from . import portal_hr_employee_intern_request_model
from . import portal_hr_expensive_request_model
from . import portal_inovice_requests_model
from . import portal_project_end_request_model
from . import portal_project_requests_model
from . import portal_purchase_order_requests_model
from . import type_approval
from . import document_approval
from . import portal_request_dashboard
from . import res_users
from . import report_certificate
from . import work_group
from . import account_analytic_inherit
from . import account_move_inherit
